# Generated by Django 4.2 on 2023-05-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pymap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("mapping_date", models.DateField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(name="Mapping",),
    ]
