# Generated by Django 4.2 on 2023-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pymap", "0005_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply", name="date", field=models.DateTimeField(),
        ),
    ]
