# Generated by Django 4.2 on 2023-05-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pymap", "0007_contactform_e_contactform_i_delete_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingPoint_I",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(old_name="MappingPoint", new_name="MappingPoint_E",),
    ]
